[package]
name = "hecto"
version = "0.1.0"
edition = "2021"
authors = ["Shawn Gao Zishuo <li-shuo@live.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
